# Assignment 5.1

Name: Steve Amancha   
Date: June 11th 

For this assignment, you will refer to the textbook to solve the practice exercises. **Use Python to answer any coding problems (not R, even if indicated in your textbook).** Use Jupyter Notebook, Google Colab, or a similar software program to complete your assignment. Submit the assignment as a PDF file. Always label your axes and provide titles for any graphs generated on this assignment. Round all quantitative answers to 2 decimal places.

## Problem 5.1.

Introducing notation for a parameter, state the following hypotheses in terms of the parameter
values and indicate whether it is a null hypothesis or an alternative hypothesis.

(a) The proportion of all adults in the UK who favor legalized gambling equals 0.50.


Null hypothesis - H0: p = 0.50


(b) The correlation for Australian adults between smoking (number of cigarettes per day) and blood pressure is positive.

Alternative hypothesis - Ha: population correlation > 0 

(c) The mean grade point average this year of all college graduates in the U.S. is the same for females and males.

Null hypothesis - H0: mean_male = mean_females

## Problem 5.2.

When a government does not have enough money to pay for the services that it provides, it can raise taxes or it can reduce services. When the Florida Poll asked a random sample of 1200 Floridians which they preferred, 52 percent (624 of the 1200) chose *raise taxes* and 48 percent chose *reduce services*. Let $\pi$ denote the population proportion of Floridians who would choose raising taxes. Analyze whether this is a minority of the population $(\pi < 0.50)$ or a majority $(\pi > 0.50)$ by testing $H_0: \pi = 0.50$ against $H_a: \pi \ne 0.50$. Interpret the *P*-value. Is it appropriate to "accept $H_0 $?" Why or why not?

Testing Null Hypthoesis: 
H0: pi = .5

Testing Alternative Hypothesis
Ha: pi ~= .5

With a p value of 0, we have very strong evidence to conclude that the true population proportion of Floridians who would choose raising taxes is not 50%.

No it's no approriate to accept H0 because instead we would reject the null hypothesis and conclude that the population proportion is different from 50%, which would agree with the alternative hypothesis. 

In [1]:
import scipy.stats as stats
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.proportion import proportions_ztest

In [93]:
# defining givens
floridians = 12000
yes_up_taxes = 624
up_taxes_prop = .52
pi = 0.5
significance = 0.05

# calculating z and p using formulas
z = (up_taxes_prop - pi) / np.sqrt((pi * (1 - pi)) / floridians)
print("z score", z)

p_value = 2 * (1 - stats.norm.cdf(abs(z)))
print(f"P value {p_value:.4f}")


# Additional testing way 
test_stat, pval = proportions_ztest(count=yes_up_taxes, nobs=floridians, value=pi, alternative='two-sided')
print('Two sided z-test: z = {:.4f}, p value = {:.4f}'.format(test_stat, pval))

if pval > significance:
   print ("Fail to reject the null hypothesis - we have nothing else to say")
else:
   print ("Reject the null hypothesis - suggest the alternative hypothesis is true")

z score 4.381780460041333
P value 0.0000
Two sided z-test: z = -221.0359, p value = 0.0000
Reject the null hypothesis - suggest the alternative hypothesis is true


## Problem 5.6.

Before a Presidential election, polls are taken in two swing states. The Republican candidate
was preferred by 59 of the 100 people sampled in state A and by 525 of 1000 sampled in state
B. Treat these as independent binomial samples, where the parameter $\pi$ is the population
proportion voting Republican in the state.


(a) If we can treat these polls as if the samples were random, use significance tests of $H_0$:
$\pi  = 0.50$ against $H_a:  \pi > 0.50$ to determine which state has greater evidence supporting a
Republican victory. Explain your reasoning.


Assuming: 
Independent binomial samples 

Because there is a smaller p value in State A, that state has a greater chance for a republican victory. We can reject the null hypthesis and support the alternative hypothesis that the population proportion > .50.

In [94]:
# Givens and assumptions
significance = 0.05
pi = 0.5
a_state_prop = 59 / 100
b_state_prop = 525 / 1000

# calculating z and p score 
z_score_a, p_value_a = proportions_ztest(59, 100, pi, alternative='larger')
z_score_b, p_value_b = proportions_ztest(525, 1000, pi, alternative='larger')

print('State A z-test: z = {:.2f}, p value = {:.2f}'.format(z_score_a, p_value_a))
print('State B z-test: z = {:.2f}, p value = {:.2f}'.format(z_score_b, p_value_b))


State A z-test: z = 1.83, p value = 0.03
State B z-test: z = 1.58, p value = 0.06


(b) Conduct a Bayesian analysis to answer the question in (a) by finding in each case the
posterior $P(\pi < 0.50)$, corresponding to the *P-* value in (a). Use beta(50, 50) priors, which
have standard deviation 0.05 and reflect the pollster’s strong prior belief that $\pi$ almost
surely is between 0.35 and 0.65. Explain any differences between conclusions.

state A probability that pi < 0.5 0.37   
state B probability that pi < 0.5 0.40   
Pi does fall into the expected range. In this case that probability are not the same which means that state b is more likely to have more even results. 

In [103]:
# Givens
beta = (50,50)
std_dev = 0.05 
pi = .5
con_int = [0.35, 0.65]

z_A = 1.83
p_val_A = 0.03
n_A = (z_A / np.sqrt((1 - 2*p_val_A))) ** 2  # approximate sample size using z score and p-value
x_A = z_A * np.sqrt(n_A*pi*(1 - pi)) + n_A*pi  # approximate number of successes using z score and sample size

# Posterior parameters
a_post_A = 50 + x_A
b_post_A = 50 + n_A - x_A

# Probability that pi < 0.5 for state A
P_A = stats.beta.cdf(0.5, a_post_A, b_post_A)
print("state A probability that pi < 0.5 {:.2f}".format(P_A))

z_B = 1.58
p_val_B = 0.06
n_B = (z_B / np.sqrt((1 - 2*p_val_B))) ** 2
x_B = z_B * np.sqrt(n_B*pi*(1 - pi)) + n_B*pi

# Posterior parameters
a_post_B = 50 + x_B
b_post_B = 50 + n_B - x_B

# Probability that pi < 0.5 for state B
P_B = stats.beta.cdf(0.5, a_post_B, b_post_B)
print("state B probability that pi < 0.5 {:.2f}".format(P_B))

state A probability that pi < 0.5 0.37
state B probability that pi < 0.5 0.40


## Problem 5.8.

For the `Students` data file at the text website, analyze political ideology.

(a) Test whether the population mean $\mu$ differs from 4.0, the moderate response. Report the
*P*-value, and interpret. Make a conclusion using $\alpha$ - level = 0.05.

Yes the population mean (3.03) differs from the moderate 4.0   
The P-value (0.00) is the two-tail probability, presuming H0 is true, that T would exceed -4.60 in absolute value.   
Since p val < 0.05 I would reject the null hypothesis and conclude that the population mean is different from 4.0  
Political Ideology: ideol = political ideology (1 = very liberal, 4 = moderate, 7 = very conservative)  

In [31]:
data_url = 'https://stat4ds.rwth-aachen.de/data/Students.dat'
students_data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(students_data)
mu = 4

# calculating needed values
data = df['ideol'].to_numpy()
ideol_se = stats.sem(data)
ideol_mean = df['ideol'].mean()
ideol_std_dev = df['ideol'].std()
ideol_size = len(df['ideol'])
df = ideol_size - 1

print(f"Se: {ideol_se:.2f}")
print(f"Mean: {ideol_mean:.2f}")
print(f"Std Deviation: {ideol_std_dev:.2f}")
print()

# Confirming standar error with formula, solving for t and p value
se = round(ideol_std_dev / np.sqrt(ideol_size), 2) 
t = (ideol_mean - mu) / se
p_val = stats.t.sf(np.abs(t), df) * 2 
print(f"se value: {se:.2f}", )
print(f"t value: {t:.2f}", )
print(f"p value: {p_val:.2f}")

Se: 0.21
Mean: 3.03
Std Deviation: 1.64

se value: 0.21
t value: -4.60
p value: 0.00


(b) Construct the 95% confidence interval for $\mu$. Explain how results relate to those of the
test in (a).


There is a 95% chance that the confidence interval of [2.62, 3.45] contains the true population mean ideology value 

In [33]:
# finding confindence interval 
ci = stats.norm.interval(confidence=0.95, loc=ideol_mean, scale=ideol_se)
print(f"Confidence Interval: {ci}")

Confidence Interval: (2.619349519812402, 3.4473171468542643)


## Problem 5.10.

A study of sheep mentioned in Exercise 1.27 analyzed whether the sheep survived for a year
from the original observation time (1 = yes, 0 = no) as a function of their weight (*kg*) at the
original observation. Stating any assumptions including the conceptual population of interest,
use a *t* test with the data in the Sheep data file at the text website to compare mean weights
of the sheep that survived and did not survive. Interpret the *P*-value.

Assumptions:

The conceptual population of interest are living pigs and their associated weight. 


The null hypothesis is that the two groups have the same population mean weight, and the alternative hypothesis is that the two groups have different population mean weights.

In [48]:
data_url = 'https://stat4ds.rwth-aachen.de/data/Sheep.dat'
sheep_data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(sheep_data)

# Creating 
survived_df, lost_df = df[df['survival'] == 1], df[df['survival'] == 0]
print("Survived pigs mean weight", round(survived_df['weight'].mean(),2))
print("Lost pigs mean weight", round(lost_df['weight'].mean(), 2))

t_stat, p_val = stats.ttest_ind(survived_df['weight'], lost_df['weight'])
print(f"t value = {t_stat:.2f}, p val = {p_val:.2f}")

Survived pigs mean weight 20.65
Lost pigs mean weight 16.0
t value = 14.50, p val = 0.00


## Problem 5.11.

Use descriptive statistics and significance tests to compare the population mean political ideology for each pair of groups in Table 5.2 using the `Polid` data file. Summarize results using
*P*-values and using a non-technical explanation.

An almost zero P-value (less than 0.05) indicates that there is a significant difference in mean political ideology between the two groups being compared. For black against white/hispanics there was a significant difference in their mean ideology.  
Not enough evidence to show different ideology between hispanic and whites. 


Hispanic v Black t stat / p value: t = 2.81, p value = 0.01   
Hispanic v White t stat / p value: t = -0.99, p value = 0.32   
Black v White t stat / p value: t = -4.34, p value = 0.00  

In [63]:
# Read and create data frame
data_url = 'https://stat4ds.rwth-aachen.de/data/Polid.dat'
sheep_data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(sheep_data)

# seperated by race dataframes
his_df, blk_df, white_df = df[df['race'] == 'hispanic'], df[df['race'] == 'black'], df[df['race'] == 'white']

# T-test for the means of two independent samples
t_stat, p_val = stats.ttest_ind(his_df['ideology'], blk_df['ideology'])
print('Hispanic v Black t stat / p value: t = {:.2f}, p value = {:.2f}'.format(t_stat, p_val))

t_stat, p_val = stats.ttest_ind(his_df['ideology'], white_df['ideology'])
print('Hispanic v White t stat / p value: t = {:.2f}, p value = {:.2f}'.format(t_stat, p_val))

t_stat, p_val = stats.ttest_ind(blk_df['ideology'], white_df['ideology'])
print('Black v White t stat / p value: t = {:.2f}, p value = {:.2f}'.format(t_stat, p_val))

Hispanic v Black t stat / p value: t = 2.81, p value = 0.01
Hispanic v White t stat / p value: t = -0.99, p value = 0.32
Black v White t stat / p value: t = -4.34, p value = 0.00


## Problem 5.14 (a).

The `Income` data file at the book’s website shows annual incomes in thousands of dollars for
subjects in three racial-ethnic groups in the U.S.

(a) Stating all assumptions including the relative importance of each, show all steps of a significance test for comparing population mean incomes of Blacks and Hispanics. Interpret.


Assumptions: 
Random normal population dist. each group - to ensure there was no bias in the population
Equal variances - The variances of income in the two groups are equal
Two populations are large enough and of equal length. 
Two groups are independent

Hypothesis:
HO : mean1 = mean2  
HA : mean1 ~= mean2  

Hispanic Mean: 31.00   
Black Mean: 27.75  

Hispanic v Black mean income: t stat / p value: t = 0.68, p value = 0.50  

With such a high p value, we fail to reject the null hypothesis. There's no significant evidence to suggest a difference in mean income between Hispanics and Blacks. 



In [78]:
data_url = 'https://stat4ds.rwth-aachen.de/data/Income.dat'
data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(data)
# display(df)

# seperating into data frames by race
his_df, blk_df = df[df['race']== 'H'], df[df['race']== 'B']

# finding and printing mean
h_income_mean = his_df['income'].mean()
b_income_mean = blk_df['income'].mean()
print(f"Hispanic mean income: {h_income_mean:.2f}")
print(f"Black mean income: {b_income_mean:.2f}")

# Performing T-test for the means of two independent samples
t_stat, p_val = stats.ttest_ind(his_df['income'], blk_df['income'])
print('Hispanic v Black t stat / p value: t = {:.2f}, p value = {:.2f}'.format(t_stat, p_val))


if p_val < 0.05:
    print("We reject the null hypothesis. Evidence suggests there is a significant difference in mean income between Hispanics and Blacks.")
else:
    print("We fail to reject the null hypothesis. There's no significant evidence to suggest a difference in mean income between Hispanics and Blacks.")

Hispanic Mean: 31.00
Black Mean: 27.75
Hispanic v Black t stat / p value: t = 0.68, p value = 0.50
We fail to reject the null hypothesis. There's no significant evidence to suggest a difference in mean income between Hispanics and Blacks.


## Problem 5.15.

A recent report $\text{}^{39}$ estimated mean adult heights in the U.S. of 175.4 *cm* (69.1 inches) for men
and 161.7 *cm* (63.7 inches) for women, with standard deviation about 7 *cm* for each group. For
all finishers in the Boston Marathon since 1972, the time to finish has a mean of 221 minutes
for men and 248 minutes for women, each with a standard deviation of about 40 minutes.
According to the effect size, is the difference between men and women greater for height or for
marathon times? Explain.

The effect size between men and women fo HEIGHT was greater than for marathon times. The effect size for height was about 2, anything over 1 is considered a large effect size. In comparison marathon times were only 0.68. 

In [104]:
# givens 
m_height = 175.4
f_height = 161.7
std = 7

m_finish_mean_mins = 221
w_finish_mean_mins = 248
finish_std_dev = 40

# calculating effect size using formula
effect_size = (m_height - f_height) / std
print(f"Height {effect_size:.2f}")

effect_size = (w_finish_mean_mins - m_finish_mean_mins) / finish_std_dev
print(f"Marathon times {effect_size:.2f}")

Height 1.96
Marathon times 0.68


## Problem 5.17.

Ideally, results of a statistical analysis should not depend greatly on a single observation. In a
sensitivity study, we re-do the analysis after deleting an outlier from the data set or changing its
value to a more typical value and checking whether results change much. For the anorexia data
analysis in Section 5.3.2, the weight change of 20.9 pounds for the cb group was a severe outlier.
Suppose this observation was actually 2.9 pounds but recorded incorrectly. Find the *P*-value
for testing $H_0: \mu1 = \mu2$ against $H_a: \mu1 \ne \mu2$ with and without that observation. Summarize its
influence.

With and without the corrected weight change, the difference produced for the p value = 0.73

We fail to reject the null hypothesis. There's no significant evidence to suggest a difference in mean weight. The change of one value can alter the p value significantly, especially in a small sample size. 

In [105]:
# Getting data
data_url = 'https://stat4ds.rwth-aachen.de/data/Anorexia.dat'
data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(data)

# sorting into the groups
cb_df , c_df = df[df['therapy'] == 'cb'], df[df['therapy'] == 'c']

cb_group_corrected = cb_df.copy()
cb_group_corrected['change'] = cb_group_corrected['after'] - cb_group_corrected['before']
control_df = cb_group_corrected.copy()
# doing replacement of value
cb_group_corrected['change'].replace(to_replace=20.900000000000006, value=2.9, inplace=True)

t_stat, p_val = stats.ttest_ind(control_df['change'], cb_group_corrected['change'])
print('t = {:.2f}, p value = {:.2f}'.format(t_stat, p_val))

t = 0.34, p value = 0.73


## Problem 5.19.

In the 2018 General Social Survey, when asked whether they believed in life after death, 1017 of 1178 females said *yes*, and 703 of 945 males said *yes*. Test that the population proportions are equal for females and males. Report and interpret the *P*-value.

Hypothesis:   
H0: mu1 = mu2  
Ha: mu1 > mu2 or mu1 < mu2  

With a P value of basically 0, we reject the null hypothesis and accept the alternative hypothesis. Evidence suggests there is a significant difference for the population proportions for males and females are not equal.


In [108]:
# creating proportions
success_cnts = np.array([1017, 703])
total_cnts = np.array([1178, 945])

test_stat, pval = proportions_ztest(count=success_cnts, nobs=total_cnts, alternative='two-sided')
print('Two sided z-test: z = {:.2f}, p value = {:.2f}'.format(test_stat, pval))



Two sided z-test: z = 6.97, p value = 0.00


## Problem 5.23.

Use the `Happy` data file from the 2018 General Social Survey at the text website to form a
contingency table that cross classifies happiness with gender. For $ H_0 $: independence between
happiness and gender:

(a) Conduct and interpret the chi-squared test.

The p-value is 0.63  
There is no relationship between the variables and it is possible the two can be independent from each other.

In [84]:
from scipy.stats import chi2_contingency


data_url = 'https://stat4ds.rwth-aachen.de/data/Happy.dat'
data = pd.read_csv(data_url, delim_whitespace=True)
df = pd.DataFrame(data)

gender_table = pd.crosstab(df['gender'], df['happiness'])
print(gender_table)
print(' ')


# print('Chi-square statistic = {:.2f}'.format(chi2))
# print('p-value = {:.4f}'.format(p_val))

def chisquare_test(table):
    stat, p_value, dof, expected = chi2_contingency(table, correction=False)
    # Interpret p-value
    alpha = 0.05

    print("The p-value is {:.2f}".format(p_value))
    if p_value <= alpha:
        print('There is a relationship between the variables.')
    else:
        print('There is no relationship between the variables.')
    return p_value, expected

chisquare_test(gender_table)


happiness    1    2    3
gender                  
female     353  642  153
male       295  553  146
 
The p-value is 0.63
There is no relationship between the variables.


(0.6323793708278013,
 array([[347.29411765, 640.45751634, 160.24836601],
        [300.70588235, 554.54248366, 138.75163399]]))

(b) Show the estimated expected frequencies and standardized residuals, and form a mosaic
plot. Explain how they are consistent with the result of the chi-squared test.

They are consisted with the chi-squared test because this p value (1) come to the same conclusion which is
There is no relationship between the variables and it is possible the two can be independent from each other.

Expected :   
 [[0.30213599 0.55778574 0.14007827]   
 [0.30213599 0.55778574 0.14007827]]   
Residuals :   
 [[ 0.00974278  0.00193842 -0.01817674]  
 [-0.00974278 -0.00193842  0.01817674]]  

In [86]:
import statsmodels.api as sm


norm_gender_table = pd.crosstab(df['gender'], df['happiness'], normalize='index')
pval , expected = chisquare_test(norm_gender_table)
print(f"Expected : \n {expected}")

residuals = (norm_gender_table - expected) / np.sqrt(expected)
print(f"Residuals : \n {residuals.values}")

# Ran out of time to figure out mosiac plot

# # Prepared data for visualization
# def percent_of_total(second_column):
#     percent_of_total = afterlife.groupby(['postlife', second_column]).size().unstack()
#     for i in range(len(percent_of_total)):
#         percent_of_total.iloc[i,:] = percent_of_total.iloc[i,:]/sum(percent_of_total.iloc[i,:])
#     return percent_of_total
# # Visualize relationship between afterlife and religion/gender
# fig, [[ax1, ax2], [ax3, ax4]] = plt.subplots(2, 2, figsize=(15, 12))
# # Count for religion and afterlife
# afterlife.groupby(['postlife', 'religion']).size().unstack().plot(ax=ax1, kind='bar', stacked=True, xlabel='Belief in Afterlife', 
#                                                                   ylabel='Frequency', title='Survey Responses - Belief in Afterlife by Religion (Count)')
# # Percentage for religion and afterlife
# religion = percent_of_total('religion')
# religion.plot(ax=ax2, kind='bar', stacked=True, xlabel='Belief in Afterlife', 
#               ylabel='Percentage', title='Survey Responses - Belief in Afterlife by Religion (Percentage)')
# # Count for gender and afterlife
# afterlife.groupby(['postlife', 'gender']).size().unstack().plot(ax=ax3, kind='bar', stacked=True, xlabel='Belief in Afterlife', 
#                                                                 ylabel='Frequency', title='Survey Responses - Belief in Afterlife by Gender (Count)')
# # Percentage for religion and afterlife
# gender = percent_of_total('gender')
# gender.plot(ax=ax4, kind='bar', stacked=True, xlabel='Belief in Afterlife', 
#             ylabel='Percentage', title='Survey Responses - Belief in Afterlife by Gender (Percentage)')
# plt.show()


The p-value is 1.00
There is no relationship between the variables.
Expected : 
 [[0.30213599 0.55778574 0.14007827]
 [0.30213599 0.55778574 0.14007827]]
Residuals : 
 [[ 0.00974278  0.00193842 -0.01817674]
 [-0.00974278 -0.00193842  0.01817674]]


## Problem 5.35.

Are many medical "discoveries" actually Type I errors? In medical research, suppose $^{43}$ that an actual population effect exists only 10\% of the time and that when an effect truly exists, the chance of making a Type II error and failing to detect it (perhaps because of insufficient sample size) is 0.50. Given that a test is significant at the 0.05 level, use Bayes theorem to show that 47\% of such studies are actually reporting Type I errors.

Given test sig at 0.05, 47% of studies actually reported type 1 errors

In [92]:
# Reporting problem givens 
P_E = 0.1  # Probability that a true effect exists
P_TypeII_given_E = 0.5  # Probability of making a Type II error given that an effect exists
P_TypeI_given_notE = 0.05  # Probability of making a Type I error given that there is no effect

P_notE = 1 - P_E  # Probability that there is no effect
P_sig_given_E = 1 - P_TypeII_given_E  # Probability that a test is significant given that there is an effect
P_sig_given_notE = P_TypeI_given_notE  # Probability that a test is significant given that there is no effect

# Total probability that a test is significant
P_sig = P_E * P_sig_given_E + P_notE * P_sig_given_notE

# Probability that a Type I error is made given that a test is significant
P_TypeI_given_sig = P_notE * P_TypeI_given_notE / P_sig

print('{:.2f}'.format(P_TypeI_given_sig))

0.47


&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;


----------------
$^{39}$ See www.cdc.gov/nchs/data/nhsr/nhsr122-508.pdf and https://doi.org/10.1371/journal.pone.  

$^{43}$ These hypothetical percentages were used in an article about this issue by J. Sterne, G. Smith, and D. R. Cox, BMJ, **322**: 226-231 (2001).